apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-api-config
data:
  RabbitMq__Host: rabbitmq
  RabbitMq__Username: guest
  RabbitMq__UserCreatedQueue: notifications-user-created
  RabbitMq__PaymentProcessedQueue: notifications-payment-processed
